version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: panzer
      POSTGRES_PASSWORD: boobs
      POSTGRES_DB: hackrush
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prisma:
    image: prismagraphql/prisma:2.11.0
    environment:
      PRISMA_CONFIG: |
        port: 5555
        databases:
          default:
            connector: postgres
            host: postgres
            database: hackrush
            user: panzer
            password: boobs
    depends_on:
      - postgres
    ports:
      - "5555:5555"   
volumes:
  postgres-data:
